[package]
name = "pqrs"
version = "0.2.0"
authors = ["Manoj Karthick"]
description = "Apache Parquet command-line tools and utilities"
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/manojkarthick/pqrs"
repository = "https://github.com/manojkarthick/pqrs"
keywords = ["cli", "arrow", "parquet"]
categories = ["command-line-utilities"]

[dependencies]
thiserror = "1.0.22"
log = "0.4.11"
env_logger = "0.8.2"
parquet = { version = "4.3.0", features = ["cli"] }
arrow = "4.3.0"
clap = "2.33.3"
rand = "0.8.3"
tempfile = "3.2.0"
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"
